spring:
  application:
    name: learner-user-api
  profiles:
    active: dev
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    #    password: Learner@2023
    #    url: jdbc:mysql://34.29.125.76:3306,34.68.236.8:3306/learnerCrownClothing?useSSL=FALSE
    password: root
    url: jdbc:mysql://localhost:3306/product_managment?useSSL=FALSE
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 8232
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    password: Vishnu@7674
    url: jdbc:mysql://34.69.195.144:3306/learnerCrownClothing?useSSL=FALSE
    username: db_user
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 8232
eureka:
  client:
    serviceUrl:
      defaultZone: http://34.138.241.187:5761/eureka/
  #instance:
    #preferIpAddress: true
